### ISSUE TITLE
Parking

### ISSUE THREAD

**Issue by botikdd** [botikdd/Jvaaref-ubbse2017#42]
Implementing a hardcoded parking algorithm (backward or paralell parking)

**Comment by mocanzaki** [comment]
Data:

               LEFT   | RIGHT
angle        -24   |    24
speed        -8.0 | -8.0
time           8.4  | 9.58 s
diameter   125 | 140 cm
battery      100 | 100 %

**Comment by mocanzaki** [comment]
FYI: Code on branch named Parking
