### ISSUE TITLE
Defining car's limits

### ISSUE THREAD

**Issue by botikdd** [botikdd/Jvaaref-ubbse2017#43]
Measuring the diagonal of the turning circle, and the time for this in the slowest speed

**Comment by mocanzaki** [comment]
Ez bovebben mi a jo az? Milyen limitek?

**Comment by botikdd** [comment]
Amit mondtál volt, hogy minimum sebességgel leméred a leírt kör átmérőjét, illetve az időt,ami alatt ezt megteszi az autó

**Comment by mocanzaki** [comment]
direction LEFT | RIGHT
angle -24 | 24
speed -8.0 | -8.0
time 8.4 | 9.58 s
diameter 125 | 140 cm
battery 100 | 100 %

**Comment by mocanzaki** [comment]
Reverse direction.
direction LEFT | RIGHT
angle -24 | 24
speed 8.0 | 8.0
time 9.65 | 9.65 s
diameter 130 | 130 cm
battery 100 | 100 %
